### ISSUE TITLE
How to use this image?

### ISSUE THREAD

**Issue by mattgphoto** [GregYankovoy/docker-goaccess#1]
Hello there! I've come across this repo as a better/more intuitive alternative to the official goaccess install. Unfortunately, it's not clear as to how to use this/install/etc. :-) Could you include a note perhaps as to how to use what you've created/modified here?

**Comment by GregYankovoy** [comment]
Thanks for opening this. I've been meaning to get update the documentation for non-unraid users.  

Take a look at what I've included and let me know if it helps you get up and running.

**Comment by mattgphoto** [comment]
You are a gentleman and a scholar! I'm spinning up a docker install to give this a shot today! I'll let you know the results!

**Comment by mattgphoto** [comment]
Holy crap. It just worked, pretty much exactly as you wrote! This is 1000x easier than the official goaccess repo, and you're far more responsive! Thank you!

**Comment by GregYankovoy** [comment]
Happy to help! Let me know if you run into any issues or missed functionality.
