### ISSUE TITLE
error log permission denied

### ISSUE THREAD

**Issue by landcraft** [GregYankovoy/docker-goaccess#13]
I've got goaccess reading my SWAG nginx logs, and goaccess says ```nginx: [alert] could not open error log file: open() "/var/lib/nginx/logs/error.log" failed (13: Permission denied)``` which is especially strange as both SWAG and goaccess are run by the same user, so I presumed permissions would not be an issue.

Access logs are read fine, as I can see stats in the goaccess dashboard.

**Comment by jarbelix** [comment]
Do not delete log files. Just clear their content like this:

`find /var/www/docker/nginx-proxy-manager/data/logs/ -type f -exec truncate -s0 {} \;`
