### ISSUE TITLE
Persistent storage of statistics?

### ISSUE THREAD

**Issue by mattgphoto** [GregYankovoy/docker-goaccess#2]
Hey Greg, sorry to bug you again :-) Was curious, do you happen to have Btree set up with this at all? Persistence of statistics would be the last possible thing I could think of.

Right now once the logs rotate, all statistics are gone in goaccess.

I think this is the solution, but not sure how to... dockerize that:
https://goaccess.io/faq#installation "How to use the on-disk database instead of keeping everything in memory?"

**Comment by GregYankovoy** [comment]
Hi Matt,

Persistent storage support is a good idea.  Looks like GoAccess requires being built with a flag for btree to utilize the Tokyo Cabinet's on-disk B+ Tree package.

As far as I can tell there's no configuration available for switching types of storage at runtime, so I'm thinking of creating another tag for the container w/ the name btree.

Let me take a look at some of this and get back to you with the results.

**Comment by mattgphoto** [comment]
You are a machine, sir! I'll be happy to go over them and help test if you need any help!

**Comment by GregYankovoy** [comment]
Got around to doing some work with this.  It appears there may be some unfortunate limitations while using Docker in combination with the btree functionality.  Got a docker build going with tokyocabinet included, but getting an error early on in the launch process of GoAccess.
[https://github.com/allinurl/goaccess/issues/708](https://github.com/allinurl/goaccess/issues/708)

Looks like we may be out of luck until GoAccess gets an update or we find an alternative piece of software.

**Comment by mattgphoto** [comment]
No worries at all. I completely understand and I really appreciate your help!
