### ISSUE TITLE
Not updating in real-time

### ISSUE THREAD

**Issue by EpochalEngineer** [GregYankovoy/docker-goaccess#4]
The report does not update after the initial startup of the container.  The number of requests, tables/graphs, and the last updated timestamp all haven't updated.  Since I was playing around with the configuration, I did reset my goaccess.conf (well, moved appdata/goaccess/) in addition to removing the docker container and image completely and re-downloading with the defaults.

I also cleared access.log so the Total Requests was reset to make it clear that it wasn't updating.  

/config/html/index.html has the same modified date as when the docker was started, if that is supposed to change.  

Any ideas?

**Comment by GregYankovoy** [comment]
It would appear the data is only real time when visiting it via the nginx url http://host:7889, which was the initial goal of this container. (Gets updated via websockets)

I'm not sure what would cause the HTML file to remain static upon launch.  The default goaccess.conf deployed with this container has "real-time-html" set to true.  Perhaps it needs to be daemonized?

Are you able to get an html file that is actively modified with the native CLI version of goaccess?  Probably best to start there so we can figure out how to implement.

**Comment by EpochalEngineer** [comment]
I'm accessing it via http://host:7889 (which doesn't update), just thought the html file might be related.

**Comment by GregYankovoy** [comment]
Do you have a green light next to the gear on the goaccess page?  That indicates the websockets are properly connecting: 
![WebsocketOnlineGreen](https://user-images.githubusercontent.com/34084447/75097487-4c6f7c80-5579-11ea-9a81-6c755baa6462.png)

If you  do not have a green light, I would suggest looking at chrome developer tools / network tab to see what's going on with the websockets.  If you are connecting via http://hostname:7889, try http://ipaddress:7889.  

Let me know what you find.

**Comment by EpochalEngineer** [comment]
Thanks for that little hint, I found the issue and a workaround: https://github.com/allinurl/goaccess/issues/969

Since the issue is on goaccess's end, it's up to you if you want to close this.

And as described in the ticket, if the curl request is smaller then it works fine.  Thus when I open goaccess incognito with no cookies on that url, then I get the green dot and it correctly updates.
