### ISSUE TITLE
update to 1.4

### ISSUE THREAD

**Issue by ced455** [GregYankovoy/docker-goaccess#5]
hello could you please  made a build for 1.4  ?

https://goaccess.io/release-notes

**Comment by GregYankovoy** [comment]
Give the 1.4 tag a try.  Preliminary tests show no issues, but let me know if you encounter any.  

`gregyankovoy/goaccess:1.4`

**Comment by GregYankovoy** [comment]
Tested 1.4 for some time as an upgrade to 1.3 and independently.  No issues and pushed 1.4 to latest.
